pipeline {
    agent any

// Stage happens automatically when Jenkinsfile is downloaded
//     stage('Clone Repository') {
//             steps {
//                 // Checkout the code from the repository
//                 git clone -b develop 'https://github.com/254In61/jenkins-cicd-test.git'
//             }
//     }


//    stages {
//         stage('Install Dependencies') {
//             steps {
//                 pip install -r requirements.txt
//             }
//         }

        stage('Lint') {
            steps {
                pylint mymodules/calculator.py
                pylint scripts/run-script.py
            }
        }

//         stage('Unittests') {
//             steps {
//                 pytest
//             }
//         }

        stage('Build') {
            steps {
                echo 'Building..'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
}