# to route service to outside world
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  type: NodePort # using the type as 'NodePort' which will expose Jenkins on all kubernetes node IPs on port 32000
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000  # when browsing to any one of the Node IPs on port 32000, you will be able to access the Jenkins dashboard. http://<node-ip>:32000