# to route service to outside world
# In the above YAML file, you define your NodePort Service and then expose port 8080 of the Jenkins pod to port 30000.
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: devops-tools
spec:
  type: NodePort 
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
   selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
